SERIAL_DEV=/dev/ttyUSB0
ISP_DEV=/dev/ttyUSB1
ISP_PROG=avr109
AVRDUDE_BAUDRATE=115200
MCU=atmega128
F_CPU=16000000
DEBUG=1
CFLAGS += -DBOOTLOADER_DDR=DDRA
CFLAGS += -DBOOTLOADER_PORT=PORTA
CFLAGS += -DBOOTLOADER_PIN=PINA
CFLAGS += -DBOOTLOADER_PINNUM=PINA0
CFLAGS += -DSEND_BOOT_MESSAGE=1
